### ISSUE TITLE
非常感谢分享，可以增加个部署教程吗

### ISSUE THREAD

**Issue by SFidea** [mogoweb/AIDog#1]
非常感谢分享，可以增加个部署教程吗

**Comment by mogoweb** [comment]
你可以看看：当微信小程序遇上TensorFlow：Server端实现补充 这篇文章

**Comment by jackylee1** [comment]
请问作者可以详细写个部署教程吗？文章不太清楚。还有可以提供下训练数据和训练模型吗？inception_v3是什么格式的呢？网上下了个压缩包有几个文件在里面

**Comment by jackylee1** [comment]
simple_tensorflow_serving --model_base_path="./models/inception_v3" &
[1] 4871
[root@izbp1d10hr1jui0lyw76fsz models]# 2018-12-28 18:09:53 INFO     secret_pem: secret.pem
2018-12-28 18:09:53 INFO     model_platform: tensorflow
2018-12-28 18:09:53 INFO     auth_password: admin
2018-12-28 18:09:53 INFO     port: 8500
2018-12-28 18:09:53 INFO     log_level: info
2018-12-28 18:09:53 INFO     enable_colored_log: False
2018-12-28 18:09:53 INFO     download_inference_images: True
2018-12-28 18:09:53 INFO     reload_models: False
2018-12-28 18:09:53 INFO     enable_ssl: False
2018-12-28 18:09:53 INFO     enable_auth: False
2018-12-28 18:09:53 INFO     host: 0.0.0.0
2018-12-28 18:09:53 INFO     custom_op_paths: 
2018-12-28 18:09:53 INFO     model_config_file: 
2018-12-28 18:09:53 INFO     auth_username: admin
2018-12-28 18:09:53 INFO     gen_client: 
2018-12-28 18:09:53 INFO     session_config: {}
2018-12-28 18:09:53 INFO     enable_cors: True
2018-12-28 18:09:53 INFO     bind: 0.0.0.0:8500
2018-12-28 18:09:53 INFO     model_base_path: ./models/inception_v3
2018-12-28 18:09:53 INFO     debug: False
2018-12-28 18:09:53 INFO     secret_key: secret.key
2018-12-28 18:09:53 INFO     model_name: default
Create path to host static files: static
Traceback (most recent call last):
  File "/usr/bin/simple_tensorflow_serving", line 7, in <module>
    from simple_tensorflow_serving.server import main
  File "/usr/lib/python2.7/site-packages/simple_tensorflow_serving/server.py", line 246, in <module>
    session_config)
  File "/usr/lib/python2.7/site-packages/simple_tensorflow_serving/tensorflow_inference_service.py", line 70, in __init__
    model_versions = self.get_all_model_versions()
  File "/usr/lib/python2.7/site-packages/simple_tensorflow_serving/tensorflow_inference_service.py", line 315, in get_all_model_versions
    model_versions = tf.gfile.ListDirectory(self.model_base_path)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 487, in list_directory
    raise errors.NotFoundError(None, None, "Could not find directory")
tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory
出现这错误是怎么回事？


我没有安装tensorflow-model-server。直接用simple_tensorflow_serving


然后那个inception_v3格式是inception_v3.ckpt
